# Generated by Django 4.2.5 on 2023-09-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=200)),
                ('working', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
