# Generated by Django 4.2.5 on 2023-09-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp_id',
            new_name='emp_email',
        ),
    ]
